services:
  nginx:
    #specify the Dockerfile location to install nginx
    build: ./requirements/nginx

    #to read the static file
    volumes:
      - wp_data:/var/www/html

    #assign a name for this container
    container_name: nginx

    #port specification
    ports:
     - "443:443"

    # if container crashes, we need to restart it 
    restart: always

    networks:
      - inception_net

  wordpress:
    build: ./requirements/wordpress

    volumes:
      - wp_data:/var/www/html
   
    container_name: wordpress
    restart: always

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE} 
      MYSQL_USER: ${MYSQL_USER} 

    secrets:
      - db_password
      - credentials

    networks:
      - inception_net

  mariadb:
    build: ./requirements/mariadb

    volumes:
      - db_data:/var/lib/mysql

    container_name: mariadb
    restart: always

    #prepare for introducing the environnement variable inside .env file
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}

    secrets:
      - db_root_password
      - db_password

    networks:
      - inception_net

volumes:
  db_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${DATA_PATH}/mariadb'

  wp_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${DATA_PATH}/wordpress'

secrets:
      db_root_password:
        file: '${SECRETS_PATH}/db_root_password.txt'
      db_password:
        file: '${SECRETS_PATH}/db_user_password.txt'
      credentials:
        file: '${SECRETS_PATH}/credentials.txt'

networks:
  inception_net:
    driver: bridge
